Repository Xcov19/mycovidconnect, pull requests merged in 2020-10, with the labels that each got.

#79 Formatted README
  CONTRIBUTING.md
  README.md
Labels: Hacktoberfest, documentation, enhancement, first-timers-only, good first issue, up-for-grabs

#87 Add repo owner and name in link url
  README.md
Labels: Hacktoberfest, documentation

#85 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#98 Fix High Severity Vulnerability: CVE-2018-11499
  package.json
Labels: Hacktoberfest, security vulnerability

#88 Update App.css
  src/App.css
Labels: Hacktoberfest, needs-review

#91 clicking on logo now will take you to home page
  .gitignore
  public/logo.png
  public/main-nav-logo.png
  src/App.css
  src/components/Logo.jsx
Labels: Hacktoberfest, first-timers-only, good first issue, help wanted, up-for-grabs

#99 Update README.md
  README.md
Labels: Hacktoberfest

#116 Remove link from header component
  src/components/Header.jsx
Labels: enhancement

#119 Added rel='noreferrer noopener' to blank targets
  README.md
  src/components/Footer.jsx
Labels: Hacktoberfest

#115 README.md update
  README.md
Labels: Hacktoberfest, documentation

#110 uber integration, refactor map component, jsdocs for search and map c…
  src/App.css
  src/components/Map.jsx
  src/constants/index.js
  src/containers/Home.jsx
  src/containers/Search.jsx
Labels: enhancement, needs-review

#125 Adding urls to links for partners
  src/components/Footer.jsx
Labels: enhancement

#128 Update App.css
  src/App.css
Labels: Hacktoberfest, first-timers-only, good first issue, hacktoberfest-accepted
