Repository Xcov19/mycovidconnect, pull requests merged in 2020-11, with the labels that each got.

#123 MYC-113 #comment remove condition to show CookieDeclaration
  .github/workflows/node.js.yml
  Dockerfile
  README.md
  docker-compose.yml
  package.json
  public/cookie-icon.png
  public/cookie-icon96.png
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/components/CookieDeclaration.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/MainHOC.jsx
  src/constants/index.js
  src/containers/Search.jsx
  src/firebase/fireStore.js
  src/serviceWorker.js
  src/setupTests.js
  startup.sh
Labels: bug

#132 add command to install docker in readme
  README.md
  docker-compose.yml
Labels: documentation

#135 Dockerfile: fixes docker load on windows. App.js: loads homepage without node insertbefore issues on L27
  Dockerfile
  src/App.js
  startup.sh
Labels: bug, needs-review

#137 Feature/cloudops/gitpod
  .gitpod.yml
  .theia/launch.json
  .theia/tasks.json
  Dockerfile
Labels: enhancement, infra

#138 MYC-152 #comment adds gitpod snapshot
  README.md
Labels: documentation

#139 MYC-152 #comment adds automated setup
  .gitpod.yml
Labels: enhancement

#141 Update docker-compose.yml
  .gitpod.yml
  docker-compose.yml
Labels: enhancement

#142 MYC-153 #closes #fixes #133
  README.md
Labels: bug, enhancement

#143 add gitpod for github in yml
  .gitpod.yml
Labels: enhancement
