Repository Xcov19/mycovidconnect, pull requests merged in 2020-12, with the labels that each got.

#151 Empty State Registration
  src/App.css
  src/App.js
  src/constants/index.js
  src/containers/Search.jsx
  src/index.js
Labels: enhancement, needs-review

#156 Revert "Empty State Registration"
  src/App.css
  src/App.js
  src/constants/index.js
  src/containers/Search.jsx
  src/index.js
Labels: bug

#158 Revert 151 premalrupnur
  .gitignore
  .theia/launch.json
  .theia/tasks.json
  src/App.css
  src/constants/index.js
  src/containers/Search.jsx
  src/index.js
Labels: enhancement

#157 Resolves the footer
  .github/workflows/node.js.yml
  .gitignore
  .theia/launch.json
  .theia/tasks.json
  src/App.css
  src/App.js
  src/constants/index.js
  src/containers/Search.jsx
  startup.sh
Labels: bug, enhancement
