Repository Xcov19/mycovidconnect, pull requests merged in 2020-09, with the labels that each got.

#26 Feature/frontend/dotenv keys
  .github/workflows/node.js.yml
  package-lock.json
  package.json
  src/constants/index.js
  src/containers/Search.jsx
Labels: needs-review

#42 sets map key in env for npm run build
  package.json
Labels: enhancement

#50 Chore: setup docker flow
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  package-lock.json
  package.json
Labels: enhancement, help wanted, needs-review

#69 removes script. additional npm scripts not required.
  .github/workflows/node.js.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  startup.sh
Labels: enhancement, needs-review
