Repository Xcov19/mycovidconnect, pull requests merged in 2021-11, with the labels that each got.

#221 Add humans.txt
  public/humans.txt
  public/index.html
Labels: good first issue, up-for-grabs, Hacktoberfest, hacktoberfest-accepted

#222 moved static files to assets and updated css URL
  src/App.css
  src/assets/loading.gif
  src/assets/noresults.png
Labels: bug, good first issue, up-for-grabs, Hacktoberfest, hacktoberfest-accepted

#227 Added custom snippet for badge in Footer
  src/components/Footer.jsx
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#228 Update index.html
  public/index.html
Labels: enhancement

#229 merge feature changes
  .github/workflows/changelog.yml
  .github/workflows/csslint.yml
  README.md
  package.json
  public/humans.txt
  public/index.html
  src/App.css
  src/App.test.js
  src/__test__/Login.test.js
  src/__test__/LoginButton.test.js
  src/__test__/Nearby.test.js
  src/__test__/Profile.test.js
  src/__test__/SearchRoute.test.js
  src/assets/loading.gif
  src/assets/noresults.png
  src/components/Footer.jsx
  src/containers/Nearby.jsx
  src/containers/Profile.jsx
  src/setupTests.js
Labels: enhancement, infra

#239 fixes local test config for docker
  docker-compose.yml
  tsconfig.json
Labels: infra

#237 develop -> master
  docker-compose.yml
  src/containers/Search.jsx
  tsconfig.json
Labels: bug, infra
