Repository Xcov19/mycovidconnect, pull requests merged in 2022-07, with the labels that each got.

#264 Create .all-contributorsrc
  .all-contributorsrc
Labels: documentation, infra

#272 unintentional push removed
  .github/workflows/upload-image.yml
Labels: infra

#273 Modified base image version
  Dockerfile
Labels: good first issue, infra

#277 Create .deepsource.toml
  .deepsource.toml
Labels: enhancement, help wanted, needs-review, infra
